name: Build and test

on:
  push:
    branches: master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Download gtest and unzip archive"
        run: |
          wget https://github.com/google/googletest/releases/download/v1.15.2/googletest-1.15.2.tar.gz
          tar -xvf googletest-1.15.2.tar.gz
      - name: "Build project"
        uses: threeal/cmake-action@v2.0.0
        with:
          source-dir: .
          build-dir: build
